// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGYhzZsTwUIgDLyWEaw5miZcAotk8VgQ',
    appId: '1:975253296259:android:401f03111ad34ee241b7b6',
    messagingSenderId: '975253296259',
    projectId: 'home-services-applicatio-aefce',
    storageBucket: 'home-services-applicatio-aefce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhHiIXM-Tj9L3P36nVJ-twQbDj_gFUtBg',
    appId: '1:975253296259:ios:29b904244a3f537641b7b6',
    messagingSenderId: '975253296259',
    projectId: 'home-services-applicatio-aefce',
    storageBucket: 'home-services-applicatio-aefce.appspot.com',
    iosBundleId: 'com.home.homeservice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAreCzUB_aTwyDao90TGmu_clmdZXxzsEo',
    appId: '1:975253296259:web:cf47b49be5f3a1c541b7b6',
    messagingSenderId: '975253296259',
    projectId: 'home-services-applicatio-aefce',
    authDomain: 'home-services-applicatio-aefce.firebaseapp.com',
    storageBucket: 'home-services-applicatio-aefce.appspot.com',
  );
}
